# Generated by Django 5.2.8 on 2026-05-24 14:55

import accounts.usermanagers.tav_user_manager
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TavUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="E.164-ish phone; normalize before saving if necessary.",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?\\d{7,15}$"
                            )
                        ],
                        verbose_name="phone",
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        help_text="How the user was verified: email/google/github/linkedin/admin",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "signup_method",
                    models.CharField(
                        default="local",
                        help_text="local, google, github, linkedin, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        blank=True,
                        help_text="OAuth provider that issued identity",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider's subject id (sub) or uid",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("provider_picture", models.URLField(blank=True, null=True)),
                (
                    "provider_raw_payload",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("locked", "Locked"),
                            ("pending", "Pending Verification"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("last_failed_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_password_reset_at", models.DateTimeField(blank=True, null=True)),
                ("signup_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("signup_user_agent", models.TextField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", accounts.usermanagers.tav_user_manager.TavUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number must be exactly 11 digits.",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True,
                        default="https://i.imgur.co m/placeholder.png",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tavuser",
            index=models.Index(fields=["email"], name="accounts_ta_email_f8ccdc_idx"),
        ),
        migrations.AddIndex(
            model_name="tavuser",
            index=models.Index(
                fields=["provider_id", "auth_provider"],
                name="accounts_ta_provide_c7cc1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tavuser",
            index=models.Index(
                fields=["account_status"], name="accounts_ta_account_9eca62_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tavuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("provider_id", None), _negated=True),
                    models.Q(("auth_provider", None), _negated=True),
                ),
                fields=("provider_id", "auth_provider"),
                name="unique_provider_per_user",
            ),
        ),
    ]
